version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/jayb25/spinnaker"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "docker"